# -*- coding: utf-8 -*-
"""kadai_008_fizzbuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uI-9KAOuAJoxc_XyXCPprv_rVUqXrz2v
"""

print("整数を入力してください")
var=int(input())

#15の倍数
if var%15==0:
    print("FizzBuzz")
#5の倍数
elif var%5==0:
    print("Buzz")
#3の倍数
elif var%3==0:
    print("Fizz")
#それ以外
else:
    print(var)