# -*- coding: utf-8 -*-
"""kadai_013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOvIBaGsqgYxTC7X3gbAYJzhC53zAZD0
"""

#商品の金額を入力
a=int(input("商品の金額を入力してください。 : "))
#消費税を入力
t=int(input("消費税は何%ですか？ : "))

print(f"{a}円, {t}%")

#金額計算の関数
def add_tax(a:int,t:int)->int:
  a=int(a*(1+t/100))
  return a

#金額計算の関数の呼び出し
print(f"税込み{add_tax(a,t)}円")